### ISSUE TITLE
细节调整

### ISSUE THREAD

**Issue by mc256** [Illvili/moegirl-navbox-flatten#1]
- ［折叠］［展开］的感应区域不够大
- ［折叠］［展开］的颜色感觉像是没有建立词条链接的颜色，很多人似乎不会去点它
-    点击紫色的部分的时候，会出现按键的阴影，不知道为什么，总感觉误会了，以为整个标题都是可以感应的区域

**Comment by mc256** [comment]
如果能够家写成  
![image](https://cloud.githubusercontent.com/assets/1913688/5914266/855c7c32-a5c0-11e4-8db5-b6a59b1c4475.png)展开
或者  [＋]展开

![image](https://cloud.githubusercontent.com/assets/1913688/5914271/984f4d88-a5c0-11e4-9f50-ab5916ef755e.png)折叠
或者  [－]折叠

或许更有效

**Comment by Illvili** [comment]
- [ ] 使用更好的显示效果（+/- 或 ^/v）
- [x] 更换链接颜色和大小
- [x] 重现阴影问题，目前怀疑是`-webkit-tap-highlight-color`

**Comment by Illvili** [comment]
@masterchan 测试下看看效果

**Comment by mc256** [comment]
收到！
